name: routine_tracker_dev
services:
  dev_db:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=routine_tracker_dev
    ports:
      - "5432:5432"
    volumes:
      - dev_db_data:/var/lib/postgresql/data
  dev_redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
volumes:
  dev_db_data:
