# Generated by Django 5.1.2 on 2024-10-17 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routine',
            options={'ordering': ['name'], 'verbose_name': 'Routine', 'verbose_name_plural': 'Routines'},
        ),
        migrations.AlterModelOptions(
            name='routineentry',
            options={'ordering': ['-date'], 'verbose_name': 'Routine Entry', 'verbose_name_plural': 'Routine Entries'},
        ),
        migrations.AlterModelOptions(
            name='routinegroup',
            options={'ordering': ['name'], 'verbose_name': 'Routine Group', 'verbose_name_plural': 'Routine Groups'},
        ),
        migrations.AlterField(
            model_name='routine',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='routine',
            name='goal',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Goal'),
        ),
        migrations.AlterField(
            model_name='routine',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routines', to='routines.routinegroup', verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='routine',
            name='has_goal',
            field=models.BooleanField(default=False, verbose_name='Has a goal'),
        ),
        migrations.AlterField(
            model_name='routine',
            name='icon',
            field=models.CharField(blank=True, max_length=50, verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='routine',
            name='measure',
            field=models.CharField(blank=True, choices=[('sec', 'Seconds'), ('min', 'Minutes'), ('hrs', 'Hours'), ('rps', 'Reps'), ('sts', 'Sets')], default='sec', max_length=50, verbose_name='Measure'),
        ),
        migrations.AlterField(
            model_name='routine',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='routine',
            name='type',
            field=models.CharField(choices=[('check', 'Check'), ('time', 'Time'), ('count', 'Count')], default='check', max_length=5, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='routineentry',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='routineentry',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='routineentry',
            name='routine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='routines.routine', verbose_name='Routine'),
        ),
        migrations.AlterField(
            model_name='routineentry',
            name='value',
            field=models.PositiveIntegerField(verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='routinegroup',
            name='color',
            field=models.CharField(default='#007bff', max_length=7, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='routinegroup',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='routinegroup',
            name='icon',
            field=models.CharField(blank=True, max_length=50, verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='routinegroup',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='routinegroup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_groups', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
