# Generated by Django 5.1.2 on 2024-11-02 21:40

import markdownfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("routines", "0003_alter_routine_measure"),
    ]

    operations = [
        migrations.AddField(
            model_name="routine",
            name="description_rendered",
            field=markdownfield.models.RenderedMarkdownField(null=True),
        ),
        migrations.AlterField(
            model_name="routine",
            name="description",
            field=markdownfield.models.MarkdownField(
                blank=True,
                rendered_field="description_rendered",
                verbose_name="Description",
            ),
        ),
    ]
