# Generated by Django 5.1.2 on 2024-10-13 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dark_mode', models.BooleanField(default=None, null=True, verbose_name='Dark mode')),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('uk', 'Ukrainian')], default='en', max_length=2, verbose_name='Preferred language')),
                ('time_zone', models.CharField(default='UTC', max_length=100, verbose_name='Time zone')),
                ('profile_completeness', models.PositiveSmallIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User profile',
                'verbose_name_plural': 'User profiles',
            },
        ),
    ]
